sparta_dev:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  database: sparta
  encoding: utf8

sparta_prod:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  database: sparta
  encoding: utf8

# Add any databases whose data you want to visualize here.
# Note: they should be limited to read-only access!

sample_impala_db:
  adapter: impala
  host: 127.0.0.1
  port: 21000
  username: avibryant
